# Copyright 2025 Matteo Brambilla - TEADAL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default:
  interruptible: false


variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: registry.teadal.ubiwhere.com/teadal-public-images/opa-policy-manager:0.0.3
  DOCKER_USER_NAME: CI-token
  

before_script:
  - docker login -u "$DOCKER_USER_NAME" -p "$REGISTRY_PASSWORD" "https://registry.teadal.ubiwhere.com"
  - docker buildx create --use

stages:
  - push_image

push_image:
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  stage: push_image
  script:
    - docker buildx build --push --platform linux/amd64,linux/arm64 --progress plain -t $DOCKER_IMAGE_NAME .
    #- docker buildx build --push --platform linux/amd64 --progress plain -t $DOCKER_IMAGE_NAME .
  when: manual  